### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by eljo14** [nightsky30/koikoi#49]
Hello, 

Thanks for this game, useful to learn koi-koi.
Two things :
1) I can't see all the window (see the capture). Is there a tip to have full screen diisplay ?
2) Played cards are too small, in my own opinion (see the capture).

Thanks for reading
Joël

display 1920x1080
Ubuntu 20.04.1 LTS
Gnome 3.36.3
Display X11

![Capture d’écran de 2020-11-16 15-35-56](https://user-images.githubusercontent.com/74551159/99265639-32ba4780-2822-11eb-92fd-9f89612b7bbb.png)

**Comment by jjjjn2** [comment]
Please fix this great game but can't see much
